### ISSUE TITLE
MediaBackup from remote storage

### ISSUE THREAD

**Issue by dorianamouroux** [django-dbbackup/django-dbbackup#176]
Hi,

As far as I understand, the media backup command doesn't use the `DEFAULT_FILE_STORAGE` to find the media files. 
If the user upload goes to a remote storage, the mediabackup won't be able to find it.

**Comment by ZuluPro** [comment]
@dorianamouroux, thanks for this issue

Exactly, I am currently refactoring this part of code and we weren't hurried up to do that because:
- Backup a Cloud object storage could be a bit useless and expensive, cloud is supposed to keep data in a safe area and sometimes duplicate in other area.
- We didn't have a ``mediarestore`` command, that I wrote and now must test and merge to master

Else it must be done because:
- Some users may want to use media backups for their dev/test/stage environment
- Cloud storage isn't mandatory and some may want to backup into FTP for example.
- I imagine DBBackup as agnostic as possible and if a user can pay for download its 1GB media files each time he/she wants to make a backup, he/she could able to do.

I will push my branch about that ASAP.

**Comment by dorianamouroux** [comment]
It's true about Cloud Storage, they are good at keeping data and making internal backup.
But those uploaded file are tightly related to the database state. If we reinstall a 2 days old backup for the database, we can expect that the media files are restored the way it was 2 days ago as well.

Looking forward for the `mediarestore` !

**Comment by ZuluPro** [comment]
Hello @dorianamouroux,
I uploaded a mediarestore branch here: https://github.com/django-dbbackup/django-dbbackup/pull/178

Could you test (or look at) and say if it resolves your issue ?

**Comment by ZuluPro** [comment]
Hello @dorianamouroux 
This issue is no more relevant. Do not hesitate to give us feedback about it.
