### ISSUE TITLE
Remove old backups after few days

### ISSUE THREAD

**Issue by dorianamouroux** [django-dbbackup/django-dbbackup#205]
It would be nice to have an option to automatically remove backups after few days.
For exemple, I don't have that much memory, I have to remove by hand the oldest one when my disk is full.

**Comment by ZuluPro** [comment]
There is the ``--clean`` option to erase older ones when number is higher than ``CLEANUP_KEEP``.
It doesn't have timeout mechanisms but could make the job.

Otherwise,
Actually the DBBackup's workflow begin by a command (dbbackup, dbrestore, etc...)
We could define a timeout and detect old backups, but actually it will clean before or after backup/restore.
