### ISSUE TITLE
Stand-alone command

### ISSUE THREAD

**Issue by ZuluPro** [django-dbbackup/django-dbbackup#209]
I want to ease DBBackup usage outside of `manage.py`.

I think a standalone command could be very usefull, a bunch a python script place in `/bin/bash`. Not a simple wrapper replacing `manage.py` but real dedicated commands with maybe cfg file for `DJANGO_SETTINGS_MODULE`.

I imagine:
- `dj-dbbackup`
- `dj-dbrestore`
- `dj-mediabackup`
- `dj-mediarestore`

The benefit is for example a dev won't need to add `'dbbackup'` to its `INSTALLED_APPS`. DBBackup will act with the project settings and the command context (.cfg + args).

The previous step is #192 **Create high level API** and the next #197 **Support for dbbackup of database in Docker container**

**Comment by jonathan-s** [comment]
If someone wants to take this up, they are welcome to, and we would welcome that contribution, but it's not super necessary and it seems like no one else has commented on this in the four years since it was created. So with that I assume no one really cares too much about this, and so I'm closing this for now.
