### ISSUE TITLE
--noinput in dbrestore doesn't work

### ISSUE THREAD

**Issue by adi-** [django-dbbackup/django-dbbackup#217]
The code https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/management/commands/dbrestore.py#L85 doesn't respect `--noinput` option which is not implemented ;)

**Comment by ZuluPro** [comment]
@adi- Thanks a lot for this reporting,
I'll check an fix tonight

**Comment by ZuluPro** [comment]
@adi- I have nothing for reproduce your bug.
As ``--noinput`` is used in functional tests I'm quite sure about it: https://github.com/django-dbbackup/django-dbbackup/blob/master/functional.sh#L12

Do you have a specific environment ?
Could you give me the output of command ?

**Comment by adi-** [comment]
I am using it as a management command:

`call_command("dbrestore", uncompress=True, servername="stg", database="default", noinput=True)`

**Comment by adi-** [comment]
...and it always asks:

`Are you sure you want to continue? [Y/n] `

**Comment by ZuluPro** [comment]
Ok, I understand now,
The keyword of `--noinput` is `interactive` : https://github.com/django-dbbackup/django-dbbackup/blob/master/dbbackup/management/commands/_base.py#L40

`call_command(... interactive=False)`

But I suggest you to use `execute_from_command_line` which reflect the command line tool.

Otherwise, in future command won't be the primary API. It will be easier to use DBBackup mechanisms without use Command objects.

**Comment by ZuluPro** [comment]
@adi- 
Any news ?

**Comment by adi-** [comment]
About? ;)

**Comment by ZuluPro** [comment]
@adi- 
Does this issue is still relevant ?
Or need a code enhancement ?

**Comment by adi-** [comment]
Ohhh, shit. I forgot to close it. Sorry!

P.S. Everything is fine and workin'!

**Comment by ZuluPro** [comment]
No pb
