### ISSUE TITLE
Issue with Django dbbackup and restore command

### ISSUE THREAD

**Issue by shashankvivek** [django-dbbackup/django-dbbackup#261]
I have 2 Databases in my app :

    DATABASES = {
        MAIL_ACCOUNTS_DB_CONFIG: {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'rango',
            'USER': 'rangoadmin',
            'PASSWORD': 'rango@2017',
            'HOST': 'localhost',  # Or an IP Address that your DB is hosted on
            'PORT': '3306',
            'OPTIONS': {'charset': 'utf8mb4'},
        },
        DEFAULT_DB_CONFIG: {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'rango',
            'USER': 'rangoadmin',
            'PASSWORD': 'rango@2017',
            'HOST': 'localhost',
            'PORT': '5432',
            'CONN_MAX_AGE': 0,
        }
    }

In `setting.py`,

`DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'`
`DBBACKUP_STORAGE_OPTIONS = {'location': '/home/shan/project_bkp'}`
`DBBACKUP_GPG_RECIPIENT = 'XXXXXXXXXXXXXXX'`

When I run
>  python manage.py dbbackup --encrypt --compress

I can only see `default-shan-desktop-2017-09-12-213553.psql.gz.gpg` . Where is the backup of mysql DB` ?

**Question:**

1. **How to know which database backup has been made** ? When I fire

>  python manage.py dbbackup --encrypt --compress --database MAIL_ACCOUNTS_DB_CONFIG

I get `django.db.utils.ConnectionDoesNotExist: The connection MAIL_ACCOUNTS_DB_CONFIG doesn't exist

2. **How to backup each DB seperately** ?

3. **How to restore it** ? When restoring using 
>  python manage.py dbrestore --decrypt 

I get : `CommandError: Because this project contains more than one database, you must specify the --database option.`

When I run :

> python manage.py dbrestore --decrypt --database MAIL_ACCOUNTS_DB_CONFIG

I get: `CommandError: Database MAIL_ACCOUNTS_DB_CONFIG does not exist.
`

**Comment by ZuluPro** [comment]
Hello @shashankvivek 
Thank, I think your issue is related to PR #260 

Could you test this PR and say if it fix your problems ?
Thanks.

**Comment by shashankvivek** [comment]
Hi @ZuluPro , I tried to make changes in dbrestore.py as per [this link](https://github.com/django-dbbackup/django-dbbackup/pull/260/commits/4febc523552bbf66db032bb50eb190d8d93dbef4) but I am still getting the same error. I need to make the restore work asap , can you please tell me the stable release number which I can use for the time being.

**Comment by ZuluPro** [comment]
Hello @shashankvivek 
About your questions :

> How to know which database backup has been made ?

By default dbbackup save all present databases

> How to backup each DB seperately ?

You can choose which database you want to save with `--database` option.

> How to restore it ?

There's a bug on database restoration. This bug should be fixed in the PR


About your issue:

- Could you give the full traceback ?
- Your database seems to be configured with constants (`MAIL_ACCOUNTS_DB_CONFIG`).
   Are you sure about the values of theses contants ?

**Comment by turacosianritesh** [comment]
The PR #260 fixes the issue to an extent, please could you approve the change and merge it?

**Comment by turacosianritesh** [comment]
Yes it is ....

On Oct 15, 2017 21:59, "Anthony Monthe" <notifications@github.com> wrote:

@shashankvivek <https://github.com/shashankvivek>
Is this issue still relevant ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/django-dbbackup/django-dbbackup/issues/261#issuecomment-336723297>,
or mute the thread

**Comment by jonathan-s** [comment]
As #260 is merged I'm closing this issue.
