### ISSUE TITLE
Is ReadTheDoc up to date ?

### ISSUE THREAD

**Issue by aymericderbois** [django-dbbackup/django-dbbackup#304]
Hi,

It seems that https://django-dbbackup.readthedocs.io/en/stable/installation.html is not up to date with the last version of the documentation.

Is it possible to update it ?

Aymeric

**Comment by bittner** [comment]
@ZuluPro Could you verify the build configuration on [Readthedocs](https://readthedocs.org/projects/django-dbbackup/builds/)? The last (automatic) build was 3 years and 9 months ago. It should build automatically on each change.

**Comment by ZuluPro** [comment]
@bittner  Done!

**Comment by bittner** [comment]
@ZuluPro All but the "latest" docs builds ran. Can you trigger also "latest"?

Personally, I would remove the "master" version and use "latest" instead. Everything else seems confusing. What do you think?

**Comment by ZuluPro** [comment]
Hello @bittner 

You are right but the problem is this project only has 1/2 maintener.
I don't have the time to work on it and we are open for new members.

We could automate PR Success -> Merge Master -> Publish Pypi and docs
But backup is really a critical task and I don't want to merge or publish blindly.

**Comment by jonathan-s** [comment]
The documentation is up to date now, so that issue should no longer be there.
