### ISSUE TITLE
Use django builtin storages as storage for dbbackup

### ISSUE THREAD

**Issue by ZuluPro** [django-dbbackup/django-dbbackup#64]
I think maybe the storage part of dbbackup is redondant with Django's buitin storage system: https://docs.djangoproject.com/en/1.8/ref/files/storage/

With this we can use third app like django-storages (https://docs.djangoproject.com/en/1.8/ref/files/storage/) and get a maximum of storages without redevelop a storage system.

What do you think about it ?

**Comment by mjs7231** [comment]
This has been brought up before Django Storages was part of the actual Django framework and it was closed because we didn't want to be dependent on another project. However, now that its built it we should reconsider. A few things to be careful of:

* Make sure no storages we support actually store any information in a database. That would be bad.
* We should definetly not cut over until we can properly support all storages we currently support (Dropbox, S3, Filesystem, S/FTP).
* This will drastically change the required settings / documentation. So a major version change and all docs updated is a must.

**Comment by ZuluPro** [comment]
Ok I'll begin when I can, I will keep you aware of my fork.

**Comment by ZuluPro** [comment]
There's is one thing which I want ask:
If we use Django's built in storage, backups will stored with static or media files and will have the same right (public by default).

How to implement dbbackup's storage configuration in the most proper way?

**Comment by ZuluPro** [comment]
I've made PR #91 for support django's storage system.
I think we should deprecate all storages and add subclasses of this wrapper instead.

There's django-storages-redux project, a fork of django-storage, which created a rebirth of this project.
Many of their storages are redundant with dbbackup's ones. But they are more elaborate.
An example is how Django's file system storage is better than dbbackup's one.

**Comment by ZuluPro** [comment]
I think it can be closed with recent commit!

**Comment by ZuluPro** [comment]
I made the following PR #93 for use Django built in filesystem storage. As you write above:
- I hold the same interface and behavior but change the code inside for use Django's one
- Use `settings.DBBACKUP_STORAGE_OPTIONS`, a dict which gathers that data

But I'm writing without know what is the road map about this:
- Will we use Django storage API as default one ?
- If yes, could we consider storages are not responsibility of DBBACKUP and only put examples in doc (and maybe some storages) ?
- If no, should we use Django Storage Redux as first source of storage ? They really have a lot and tested storages and a Libcloud one which really allows to extend possibilities. Tests for public API generally ask some funds for mock out everything and the other projects has a biggest community with enterprises which work on it
