### ISSUE TITLE
Clean up file naming and base directory structure (from `/TODO.md`)

### ISSUE THREAD

**Issue by ZuluPro** [django-dbbackup/django-dbbackup#87]
Only a comment:
I think `dbbackup.storage` must be rename `dbbackup.storages`.

https://github.com/django-dbbackup/django-dbbackup/blob/5bb44b8a7ca4ae4bb973a88b44cf938431a88795/TODO.md

**Comment by benjaoming** [comment]
That doesn't really sound like a good use of time :) I'm personally not that much in favour of such refactors... life will be better if we learn to cope with this little things :)

But on the good side, you have consistence because it's called `django.core.files.storage`, and also you cannot usually count "storage" so it doesn't have a plural form in common English.
